actions:
  hover:
    player_info:
      - "&8~ &f&l%player_name%"
      - ""
      - "&6Rank&8:&f&o %vault_prefix%&r"
      - "&9Store&8:&f&o https://your.server.store"
  click:
    message:
      suggest: "/msg %player_name% "
    open_store:
      openurl: "https://your.server.store"

formats:
  default:
    allows:
      colors: false
      format: false
    format: "[&f%player_name%&r](click.message) &8»&r %message%&r"
  donator:
    allows:
      colors: true
      format: false
    format: "[%vault_prefix%&r](hover.player_info, click.open_store) [&7%player_name%&r](click.message) &8»&r %message%&r"