#
# Plugin behavior options
#

options:
  # Whether the chat listener will actually cancel the AsyncPlayerChatEvent, or just clear its recipients.
  cancel_chat_event: false
  # Extra features
  extras:
    replacers:
      # Whether the plugin should attempt to replace placeholderapi placeholders
      clip_papi: true
      # Whether the plugin should attempt to replace mvdw_placeholderapi placeholders
      mvdw_papi: true
  # Format bypassing options
  bypass:
    # Permission for whether a player can always use color codes, regardless of the format
    colors_permission: "voxchat.bypass.colors"
    # Permission for whether a player can always use format codes, regardless of the format
    format_permission: "voxchat.bypass.format"


#
# Actions are path addressable, reusable component additions.
#
# =======================================
#             Hover Template
# hover:
#   first_name:
#     # A hover with a single line
#     text: "Single Line"
#   other_name:
#     # A hover with multiple lines
#     text:
#       - "multiple"
#       - "lines"
# =======================================
#
# =======================================
#             Click Template
# click:
#   first_name:
#     # Suggest a command to the player
#     show_cmd: "/suggest this command"
#   other_name:
#      # Attempt to open a link in the player's browser
#     open_url: "https://www.google.com"
#   third_name:
#     # Execute a command as the player
#     exec_cmd: "/execute this command"
# =======================================


actions:
  hover:
    player_info:
      text:
        - "&8~ &f&l%player_name%"
        - ""
        - "&6Rank&8:&f&o %vault_prefix%&r"
        - "&9Store&8:&f&o https://your.server.store"
  click:
    message:
      show_cmd: "/msg %player_name% "
    open_store:
      open_url: "https://your.server.store"

#
# Formats can be assigned via a permission using their name
#
#
# =======================================
#             Format Template
# formats:
#   # Permission would be voxchat.format.default
#   default:
#     allows:
#       # Whether the player can use color codes
#       colors: true # default false
#       # Whether the player can use format codes
#       format: true # default false
#     # The actual format for messages sent by players
#     format: "%player_name% > %message%"
# =======================================

formats:
  default:
    allows:
      colors: false
      format: false
    format: "[&f%player_name%&r](click.message) &8»&r %message%&r"
  donator:
    allows:
      colors: true
      format: false
    format: "[%vault_prefix%&r](hover.player_info,click.open_store) [&7%player_name%&r](click.message) &8»&r %message%&r"