name: "VoxChat"
main: "com.sxtanna.mc.chat.VoxChatPlugin"

version: "@version@"
website: "https://www.sxtanna.com"
authors: ["Sxtanna"]

api-version: "1.13"
description: "Modern Minecraft Chat Management"