name: "VoxChat"
main: "com.sxtanna.mc.chat.VoxChatPlugin"

version: "@version@"
website: "@website@"
authors: ["@author@"]

api-version: "1.13"
description: "Modern Minecraft Chat Management"

commands:
  voxchat:
    description: "VoxChat Commands"
    permission: "voxchat.command"
    aliases: ["vc", "vchat"]